# Inspiration / sources:
#
# @see https://github.community/t/can-you-add-binaries-to-releases-with-github-actions/16665/8
# @see https://github.com/Blacksmoke16/oq/pull/47/files#diff-082c28d748ad2e3eecc5508d740d9417R9-R29
name: Release

on:
  release:
    types:
      - created

jobs:
  dist:
    name: Distribution (binaries)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run dist

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/linux/envsubst
          asset_name: envsubst-${{ github.event.release.tag_name }}-linux-x86_64
          asset_content_type: binary/octet-stream

      - name: Upload Linux (arm64) Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/linux-arm64/envsubst
          asset_name: envsubst-${{ github.event.release.tag_name }}-linux-aarch64
          asset_content_type: binary/octet-stream

      - name: Upload Linux (Alpine) Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/alpine/envsubst
          asset_name: envsubst-${{ github.event.release.tag_name }}-alpine-x86_64
          asset_content_type: binary/octet-stream

      - name: Upload Linux (Alpine, arm64) Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/alpine-arm64/envsubst
          asset_name: envsubst-${{ github.event.release.tag_name }}-alpine-aarch64
          asset_content_type: binary/octet-stream

      - name: Upload MacOS Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/macos/envsubst
          asset_name: envsubst-${{ github.event.release.tag_name }}-macos-x86_64
          asset_content_type: binary/octet-stream

      - name: Upload MacOS (arm64) Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/macos-arm64/envsubst
          asset_name: envsubst-${{ github.event.release.tag_name }}-macos-arm64
          asset_content_type: binary/octet-stream

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/win/envsubst.exe
          asset_name: envsubst-${{ github.event.release.tag_name }}-win-x86_64.exe
          asset_content_type: binary/octet-stream
